# Generated by Django 5.0.6 on 2024-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_login_username', models.CharField(max_length=100)),
                ('client_login_password', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
