# Generated by Django 5.0.6 on 2024-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0002_clientlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogin',
        ),
    ]
