# Generated by Django 5.0.6 on 2024-06-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_manager_email', models.EmailField(max_length=60)),
                ('add_manager_username', models.CharField(max_length=100)),
                ('add_manager_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_login_username', models.CharField(max_length=100)),
                ('manager_login_password', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
