# Generated by Django 5.0.6 on 2024-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('milestones', models.IntegerField()),
                ('description', models.TextField()),
                ('team_member', models.CharField(max_length=255)),
                ('task_to_be_allotted', models.CharField(max_length=255)),
            ],
        ),
    ]
