# Generated by Django 5.0.6 on 2024-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_project_teammembertask_delete_projecttaskallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
